name: Build Android Kernel

on:
  workflow_dispatch: # Allows you to trigger the build manually from GitHub

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential flex libcrypto++-dev libssl-dev libelf-dev profiles-extra compression-tools zip unzip perl sed

    - name: Run Kernel Build Script
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Upload Flashable Kernel Zip
      uses: actions/upload-artifact@v4
      with:
        name: Galaxy-Tab-S8-Kernel-Zip
        path: TabS8_Kernel_GKI.zip
        retention-days: 7 # Saves space by deleting the file after 7 days
